# Generated by Django 5.0.4 on 2024-04-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="id",
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
