# Generated by Django 5.0.4 on 2024-04-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_alter_author_id_alter_quote_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="quote",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
